config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'contractors#index'

  resources :contractors do
    resources :payment_requests
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contractor.rb
# frozen_string_literal: true

class Contractor < ApplicationRecord
  has_many :payment_requests

  validates :name, presence: true
  validates :email, presence: true
end

app/models/payment_request.rb
# frozen_string_literal: true

class PaymentRequest < ApplicationRecord
  belongs_to :contractor
  before_validation :set_pending_status

  after_save :publish_to_manager_dashboard

  validates :amount, presence: true
  validates :currency, presence: true
  validates :description, presence: true

  private

  def set_pending_status
    self.status = 'pending'
  end

  private

  def publish_to_manager_dashboard
    Publisher.publish('payment_requests', attributes)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contractors_controller.rb
# frozen_string_literal: true

class ContractorsController < ApplicationController
  before_action :find_contractor, only: %i[show edit update destroy]

  def index
    # GET /contractors
    @contractors = Contractor.all
  end

  def new
    # GET /contractors/new
    @contractor = Contractor.new
  end

  def create
    # POST /contractors/new
    @contractor = Contractor.new(contractor_params)

    if @contractor.save
      redirect_to contractor_path(@contractor)
    else
      render :new
    end
  end

  # GET    /contractors/:id
  def show; end

  # GET    /contractors/:id/edit
  def edit; end

  def update
    # PATCH  /contractors/:id
    # PUT  /contractors/:id
    if @contractor.update_attributes(contractor_params)

      redirect_to contractors_path
    else
      render :edit
    end
  end

  def destroy
    # DELETE /contractors/:id
    if @contractor.destroy
      redirect_to contractors_path
    else
      redirect_to contractors_path
    end
  end

  private

  def contractor_params
    params.require(:contractor).permit(:name, :email)
  end

  def find_contractor
    @contractor = Contractor.find(params[:id])
  end
end

app/controllers/payment_requests_controller.rb
# frozen_string_literal: true

class PaymentRequestsController < ApplicationController
  before_action :find_contractor
  before_action :find_payment_request, only: %i[show edit update destroy]

  def index
    # GET    /contractors/:contractor_id/payment_requests
    @payment_requests = PaymentRequest.where(contractor_id: @contractor.id)
  end

  def new
    # GET    /contractors/:contractor_id/payment_requests/new
    @payment_request = @contractor.payment_requests.new
  end

  def create
    # POST   /contractors/:contractor_id/payment_requests
    @payment_request = @contractor.payment_requests.new(payment_request_params)

    if @payment_request.save
      redirect_to contractor_payment_request_path(@contractor, @payment_request)
    else
      render :new
    end
  end

  # /contractors/:contractor_id/payment_requests/:id
  def show; end

  # GET    /contractors/:contractor_id/payment_requests/:id/edit
  def edit; end

  def update
    # PATCH  /contractors/:contractor_id/payment_requests/:id
    # PUT  /contractors/:contractor_id/payment_requests/:id
    if @payment_request.update_attributes(payment_request_params)

      redirect_to contractor_payment_requests_path
    else
      render :edit
    end
  end

  def destroy
    # DELETE /contractors/:contractor_id/payment_requests/:id
    if @payment_request.destroy
      redirect_to contractor_payment_requests_path
    else
      redirect_to contractor_payment_requests_path
    end
  end

  private

  def find_contractor
    @contractor = Contractor.find(params[:contractor_id])
  end

  def payment_request_params
    params.require(:payment_request).permit(:amount, :currency, :description, :status)
  end

  def find_payment_request
    @payment_request = PaymentRequest.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contractors_helper.rb
# frozen_string_literal: true

module ContractorsHelper
end

app/helpers/payment_requests_helper.rb
# frozen_string_literal: true

module PaymentRequestsHelper
end

app/views/contractors/index.html.erb
<% @contractors.each do |contractor| %>
  <%= link_to contractor_goals_path(contractor) do %>
    <p><%= contractor.name %></p>
    <p><%= link_to  "delete contractor", contractor_path(contractor), method: :delete, remote: true %></p>
  <% end %>
<% end %>
<br>
<%= link_to "create contractor", new_contractor_path %>

app/views/contractors/new.html.erb
<%= simple_form_for @contractor do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.button :submit %>
<% end %>

app/views/contractors/show.html.erb
<%= @contractor.name %>
<%= @contractor.email %>
<%= link_to "create payment request", new_contractor_payment_request_path(@contractor.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContractorApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payment_requests/index.html.erb
<% @payment_requests.each do |payment_request| %>
  <p><%= payment_request.amount %> - <%= payment_request.description %></p>
  <%= link_to "view payment_request", contractor_payment_request_path(payment_request.contractor_id, payment_request.id) %>
  <%= link_to  "Delete payment_request", contractor_payment_request_path(@contractor, payment_request.id), method: :delete, remote: true %>
<% end %>
<br>
<br>
<%= link_to "create payment_request", new_contractor_payment_request_path %>

app/views/payment_requests/new.html.erb
<%= simple_form_for [@contractor, @payment_request] do |f| %>
  <%= f.input :amount %>
  <%= f.input :currency %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/payment_requests/show.html.erb
<p><%= @payment_request.amount %></p>
<p><%= @payment_request.currency %></p>
<p><%= @payment_request.description %></p>
<p><%= @payment_request.status %></p>

<p><%= link_to "back to payment requests", contractor_payment_requests_path(@contractor.id, @payment_request.id) %></p>
<br>
<p><%= link_to "create payment request", new_contractor_payment_request_path %></p>